apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wildfly
  namespace: wildfly
  labels:
    app:  wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  wildfly
    spec: 
      containers:
      - name:  wildfly
        image:  microchip1987/imagenes-wildfly:v1.0
        ports:
        - containerPort:  8080
          name:  wildfly-port
          protocol: TCP